import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};
import Search from "@/app/components/pages/search/Search";
import Navbar from "@/app/components/shared/Navbar";
import WhoToFollow from "@/app/components/shared/WhoToFollow";
import TopBlogs from "@/app/components/shared/TopBlogs";
import UserCategories from "../components/shared/UserCategories";

export default async function MainPagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="relative flex w-full flex-col justify-center p-3 md:flex-row md:gap-16">
        {children}

        <aside className="sticky top-5 order-1 flex w-full flex-col gap-5 p-5 md:order-2 md:w-[27rem]">
          <Search />
          <TopBlogs />
          <WhoToFollow />
          <UserCategories />
        </aside>
      </main>
    </>
  );
}
