import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "../components/ui/toaster";
export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};

export default function MainPagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
        </head>
        <body className="bg-background text-foreground selection:bg-foreground selection:text-background">
          <Navbar />
          <Toaster />
          {children}
        </body>
      </html>
    </>
  );
}
