import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};
import Navbar from "@/app/components/shared/Navbar";
import SideBar from "../components/shared/SideBar";

export default async function MainPagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="flex w-full flex-col justify-center p-3 md:flex-row md:gap-16">
        {children}
        <SideBar />
      </main>
    </>
  );
}
