import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};
import CurrentUserProvider from "@/app/providers/CurrentUserProvider";

export default async function BlogsPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <CurrentUserProvider>{children}</CurrentUserProvider>;
}
