export const categories = [
  "Political Science",
  "Software Engineering",
  "Business Intelligence",
  "Art",
  "Physics",
  "Literature",
  "Blockchain",
  "Computer Science",
  "Chemistry",
  "Digital Marketing",
  "Database Management",
  "Cybersecurity",
  "History",
  "Sociology",
  "Education",
  "Artificial Intelligence",
  "Data Science",
  "Music",
  "Geography",
  "Philosophy",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Economics",
  "Game Development",
  "Network Administration",
  "Psychology",
  "Big Data",
  "Biology",
  "Anthropology",
  "Architecture",
  "Astronomy",
  "Design",
  "Environmental Science",
  "Film Studies",
  "Health Sciences",
  "Law",
  "Linguistics",
  "Mathematics",
  "Medicine",
  "Oceanography",
  "Public Administration",
  "Religious Studies",
  "Robotics",
  "Social Work",
  "Space Exploration",
  "Sports Science",
  "Theater Arts",
  "Tourism",
  "Urban Planning",
  "Visual Arts",
  "Zoology",
  "Fashion Design",
  "Criminal Justice",
  "Philology",
  "Business Administration",
  "Dentistry",
  "Engineering",
  "Forensic Science",
  "Genetics",
  "Humanities",
  "Information Systems",
  "International Relations",
  "Marketing",
  "Microbiology",
  "Nursing",
  "Paleontology",
  "Parapsychology",
  "Political Economy",
  "Quantum Physics",
  "Radiology",
  "Sustainability",
  "Veterinary Medicine",
  "Wildlife Conservation",
  "Xenobiology",
  "Yoga Studies",
  "Zymology",
  "Astrobiology",
  "Bioinformatics",
  "Cognitive Science",
  "Demography",
  "Ethnomusicology",
  "Folklore",
  "Gerontology",
  "Horticulture",
  "Immunology",
  "Kinesiology",
  "Liberal Arts",
  "Meteorology",
  "Neuroscience",
  "Optometry",
  "Petrology",
  "Quantitative Finance",
  "Rheumatology",
  "Statistics",
  "Telecommunications",
  "Urban Studies",
  "Virology",
  "Wine Studies",
  "X-ray Crystallography",
  "Youth Development",
  "Zebrafish Biology",
]
