import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};

import SideBar from "@/app/components/shared/SideBar";

export default async function MainPagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex w-full flex-col justify-center p-8 md:flex-row md:gap-8">
      {children}
      <SideBar />
    </main>
  );
}
