import {QueryClient, QueryClientProvider} from "@tanstack/react-query"
import {ThemeProvider} from "./Components/ThemeProvider"
import type {Metadata} from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
}
const queryClient = new QueryClient()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className="bg-background text-foreground selection:text-background selection:bg-foreground overflow-x-hidden">
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </QueryClientProvider>
  )
}
