import type { Metadata } from "next";
import { getCookie } from "cookies-next";
import { cookies } from "next/headers";
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "Welcome | Post-Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = getCookie("token", { cookies });
  return (
    <>
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
        </head>
        <body className="bg-background text-foreground selection:bg-foreground selection:text-background">
          {token && <Navbar />}
          {children}
        </body>
      </html>
    </>
  );
}
